version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: yorriyurri/foodgram_project:latest
    restart: always
    volumes:
      - ../data/:/app/data/
      - backend_static:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: yorriyurri/foodgram_project_frontend:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - backend_static:/usr/share/nginx/html/backend_static/:ro
      - media_value:/usr/share/nginx/html/media/:ro
    depends_on:
      - web
      - frontend

volumes:
  db:
  backend_static:
  media_value: